[tool.poetry]
name = "carrot-executor"
version = "0.6.4"
description = "Camunda external task Robot Framework execution scheduler"
homepage = "https://github.com/datakurre/carrot-executor"
authors = ["Asko Soukka <asko.soukka@iki.fi>"]
license = "MIT"
packages = [
    { include = "*.py", from="lib" },
    { include = "carrot_executor/*.py" },
]
include = [ "carrot_executor/index.js" ]
readme = "README.md"

[tool.poetry.scripts]
carrot-executor = "carrot_executor:main"

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^4.0.3"
pydantic = "^1.8.2"
requests = "^2.25.1"
Pillow = "^8.3.0"

[tool.poetry.dev-dependencies]
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
