[tool.poetry]
name = "xml-builder"
version = "0.3.0"
description = ""
authors = ["Rafa Leblic <rafa@notin.net>"]
packages = [
  { include = 'rlc', from = 'src' },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
mypy = "^0.812"
black = "^20.8b1"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
